layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# projects:
#  sort_by: pushed
#  sort_by options:
  #   - pushed
  #   - stars
#  limit: 9
#  exclude:
#    archived: false
#    forks: true
#    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: bencegazder
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://apicore.de
  # youtube: your_username

topics:
  - name: Laravel
    web_url: https://laravel.com/
    image_url: https://laravel.com/img/logotype.min.svg

  - name: Ethereum
    web_url: https://ethereum.org/
    image_url: https://ethereum.org/assets/img/ethereum-icon-black.ea53fb22.svg

  - name: Rust
    web_url: https://www.rust-lang.org/
    image_url: https://www.rust-lang.org/static/images/rust-logo-blk.svg

  - name: C++
    web_url: http://www.cplusplus.com/
    image_url: https://raw.githubusercontent.com/isocpp/logos/master/cpp_logo.png

  - name: vue.js
    web_url: https://vuejs.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg